"""Change Charity and Donation Model

Revision ID: 3493dd74af49
Revises: bf1615de3742
Create Date: 2023-03-21 16:58:35.918578

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3493dd74af49'
down_revision = 'bf1615de3742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
